'use client';
/* eslint-disable @next/next/no-html-link-for-pages */
import {useEffect,useRef,useState} from 'react';
import {ReceiptText,Upload,Mic,ArrowUpRight,Check,Users,RotateCcw,LoaderCircle,Square,Undo2,Download,Info,AlertCircle,ChevronRight} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {Progress} from '@/components/ui/progress';
import {itemsOf,money} from '@/lib/split';
import {useTabletalk} from '@/lib/use-tabletalk';
export default function Home(){
 const app=useTabletalk();const [modal,setModal]=useState<'names'|'sample'|'photo'|'share'|null>(null);const [names,setNames]=useState(app.people.map(p=>p.name));const [nameError,setNameError]=useState('');const [shareItem,setShareItem]=useState('');const [sharers,setSharers]=useState<string[]>([]);
 const photoInput=useRef<HTMLInputElement>(null);const audioInput=useRef<HTMLInputElement>(null);
 const locked=!!app.busy||app.recording;const items=app.state?itemsOf(app.state.receipt):[];
 const cost=app.operations.reduce((n,o)=>n+(o.costUSD??0),0);const incompleteCost=app.operations.some(o=>o.costUSD===null);
 const exposedState=useRef<unknown>(null);
 useEffect(()=>{exposedState.current={receipt:app.state?.receipt??null,allocation:app.state?.allocation??{},people:app.people,verification:app.result,settled:app.settled,pending:app.pending,confirmation:app.confirmation};},[app.state,app.people,app.result,app.settled,app.pending,app.confirmation]);
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>unknown}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'get_receipt_split',title:'Read the receipt split',description:'Read the current receipt, owners, totals and unresolved clarifications. Does not modify the split.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input:unknown){if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object.');return exposedState.current;}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[]);
 function openShare(id:string){setShareItem(id);setSharers(app.state?.allocation[id]?.length?app.state.allocation[id]:app.people.map(p=>p.id));setModal('share');}
 return <main className="app-shell">
  <header className="topbar"><a className="brand" href="/"><span className="brand-icon"><ReceiptText size={23}/></span>tabletalk<span className="wordmark-dot">.</span></a><span className="edition">THE BILL, SORTED.</span><span className="scope">English · EUR</span></header>
  <section className="page-heading"><div><p className="eyebrow">A LITTLE LESS MATH AT THE TABLE</p><h1>Good food. Fair shares.</h1><p>Add your receipt. Tell us who had what.</p></div><span className="step-label"><b>01</b> Receipt <span>/</span> <b>02</b> Tell us <span>/</span> <b>03</b> Split</span></section>
  {app.configured===false&&<div className="setup-note"><Info size={18}/><span>Live photo and voice recognition needs an API key. <button disabled={locked} onClick={()=>{app.startExample();}}>Explore the allocation example</button> while it’s being connected.</span></div>}
  {app.error&&<div className="error" role="alert"><AlertCircle size={18}/><span>{app.error}</span></div>}
  <input ref={photoInput} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const file=e.target.files?.[0];if(file)void app.uploadPhoto(file);e.target.value='';}}/>
  <input ref={audioInput} hidden type="file" accept="audio/*,.wav,.mp3,.m4a,.webm" onChange={e=>{const file=e.target.files?.[0];if(file)void app.uploadAudio(file);e.target.value='';}}/>
  <div className="workspace"><section className="receipt-panel panel" aria-busy={!!app.busy}>
   <div className="panel-title"><h2><ReceiptText size={20}/>Your receipt</h2><span className="small-label">{app.state?`${app.state.receipt.rows.length} PRINTED ROWS`:'UP TO 10 ROWS'}</span></div>
   {!app.state?<div className={`upload-zone ${app.busy?'loading-zone':''}`} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!locked&&e.dataTransfer.files[0])void app.uploadPhoto(e.dataTransfer.files[0]);}}><span className="upload-icon">{app.busy?<LoaderCircle className="spin" size={28}/>:<Upload size={28}/>}</span><h3>{app.busy?'Reading the small print.':'Bring the receipt.'}</h3><p>A clear photo of the full receipt,<br/>including the total and service charge.</p><button className="primary" disabled={locked} onClick={()=>photoInput.current?.click()}>Choose a photo <ArrowUpRight size={17}/></button><span className="small-label">JPG, PNG OR WEBP · OR DROP IT HERE</span><button className="text-button" disabled={locked} onClick={()=>setModal('sample')}>Try a sample receipt</button></div>:<>
    <div className="receipt-meta"><div><p className="eyebrow">{app.example?'ALLOCATION EXAMPLE · PREFILLED':'RECOGNIZED FROM YOUR PHOTO'}</p><h3>{app.state.receipt.merchant||'Your restaurant'}</h3></div><button className="photo-thumbnail" aria-label="View original receipt photo" onClick={()=>setModal('photo')}><img src={app.photo} alt="Original receipt"/></button></div>
    <div className="receipt-toolbar"><span>{app.result?.assigned} of {items.length} items assigned</span><div><button disabled={locked||!app.history.length} onClick={app.undo}><Undo2 size={14}/>Undo</button><button disabled={locked} onClick={app.reset}><RotateCcw size={14}/>New receipt</button></div></div>
    <div className="allocation-progress"><Progress value={items.length?(app.result?.assigned??0)/items.length*100:0} aria-label="Items assigned"/></div>
    <div className="receipt-rows">{items.map(item=>{const owners=app.state!.allocation[item.id]??[];return <div className={`receipt-row ${item.uncertain||item.amountMinor===null?'uncertain':''}`} key={item.id}><div><strong>{item.name}{owners.length>1&&<span className="shared-label">shared equally</span>}</strong><span>{money(item.amountMinor)}</span></div>{(item.uncertain||item.amountMinor===null)&&<div className="row-question"><AlertCircle size={14}/><span>{item.amountMinor===null?'This price is unclear. Read the row and amount aloud, or upload a clearer photo.':'Please check this row against the photo.'}</span>{item.amountMinor!==null&&<button disabled={locked} onClick={()=>app.confirmVisibleRow(item.rowId)}>Looks correct</button>}</div>}<div className="owner-options" aria-label={`Who pays for ${item.name}?`}>{app.people.map((p,i)=><button key={p.id} disabled={locked} aria-pressed={owners.includes(p.id)} className={`owner person-${i} ${owners.includes(p.id)?'selected':''}`} onClick={()=>app.assign([{itemIds:[item.id],personIds:[p.id]}],`${item.name} → ${p.name}`)}>{owners.length===1&&owners.includes(p.id)&&<Check size={12}/>} {p.name}</button>)}<button disabled={locked} className={`owner ${owners.length>1?'selected':''}`} onClick={()=>openShare(item.id)}><Users size={13}/>Share</button>{owners.length>0&&<button disabled={locked} className="clear-owner" aria-label={`Clear owners of ${item.name}`} onClick={()=>app.assign([{itemIds:[item.id],personIds:[]}],`Cleared ${item.name}.`)}>Clear</button>}</div></div>;})}</div>
    <div className="receipt-foot"><div><span>Subtotal</span><span>{money(app.state.receipt.subtotalMinor)}</span></div><div><span>Service charge <small>split proportionally</small></span><span>{money(app.state.receipt.serviceMinor)}</span></div><div className="receipt-total"><strong>Receipt total</strong><strong>{money(app.state.receipt.totalMinor)}</strong></div></div>
    {!!app.result?.issues.filter(x=>!x.includes('still need')).length&&<div className="receipt-issues">{app.result.issues.filter(x=>!x.includes('still need')).map(issue=><p key={issue}><AlertCircle size={14}/>{issue}</p>)}<button disabled={locked} className="text-button" onClick={()=>photoInput.current?.click()}>Upload a clearer photo</button></div>}
   </>}
  </section>
  <aside className="split-column"><section className="panel people-panel"><div className="panel-title"><h2><Users size={20}/>At the table</h2><button className="quiet-button" disabled={locked} onClick={()=>{setNames(app.people.map(p=>p.name));setNameError('');setModal('names');}}>Edit names</button></div><div className="people-list">{app.people.map((p,i)=><div className="person" key={p.id}><span className={`avatar person-${i}`}>{p.name[0]}</span><strong>{p.name}</strong></div>)}</div></section>
   <section className={`voice-card ${app.recording?'recording':''}`}><div className="voice-symbol"><Mic size={25}/></div><h2>{app.recording?'We’re listening.':app.settled?'All sorted. Any changes?':'Just say who had what.'}</h2><p>{app.recording?'Tap stop when you’ve finished. Up to 60 seconds.':app.settled?'“Actually, the second coffee was Sam’s.”':`“${app.people[0].name} had the pasta. ${app.people[1].name} had the burger. We all shared the fries.”`}</p><button className="voice-button" disabled={!app.state||!!app.busy||app.configured===false} onClick={()=>void app.toggleRecording()}>{app.recording?<Square size={17} fill="currentColor"/>:app.busy?<LoaderCircle className="spin" size={18}/>:<Mic size={18}/>} {app.recording?'Stop recording':app.busy||(!app.state?'Add a receipt to begin':'Tell us who had what')}</button>{app.state&&<div className="voice-links"><button disabled={locked||app.configured===false} onClick={()=>audioInput.current?.click()}>Upload voice recording</button><button disabled={locked} onClick={()=>setModal('sample')}>Sample recordings</button></div>}<span className="voice-hint">You can change your mind. We’ll update the split.</span></section>
   {app.pending&&<section className="clarification" aria-live="polite"><p className="eyebrow">ONE QUICK QUESTION</p><h3>{app.pending.question}</h3><div className="clarification-choices">{app.pending.candidateItemIds.map(id=><button className="choice-button" disabled={locked||!app.pending?.candidatePersonIds.length} key={id} onClick={()=>app.resolveCandidate(id)}>{items.find(i=>i.id===id)?.name}<ChevronRight size={16}/></button>)}</div><p>Choose an option or answer with your voice.</p><button className="quiet-button" disabled={locked} onClick={app.dismissPending}>Discard this change</button></section>}
   {app.confirmation&&<section className="clarification" aria-live="polite"><p className="eyebrow">CHECK WHAT WE HEARD</p><h3>{app.confirmation.field==='row'?(app.confirmation.name??app.state?.receipt.rows.find(r=>r.id===app.confirmation?.rowId)?.name):app.confirmation.field.replace('Minor','')}: {money(app.confirmation.amountMinor)}</h3><p>Confirm this matches the receipt before we update it.</p><div className="clarification-choices"><button className="primary" disabled={locked} onClick={app.acceptConfirmation}>Yes, that’s correct</button><button className="quiet-button" disabled={locked} onClick={app.dismissPending}>Discard</button></div></section>}
   <section className="panel totals-panel" aria-live="polite"><div className="panel-title"><h2>Your split</h2><span className={`status ${app.settled?'settled':''}`}>{app.settled?'Balanced':app.pending||app.confirmation?'Needs clarification':'In progress'}</span></div>{(app.result?.people??app.people.map(p=>({...p,subtotal:0,service:0,total:0}))).map((p,i)=><div className="person-total" key={p.id}><span className={`avatar small person-${i}`}>{p.name[0]}</span><div><strong>{p.name}</strong><small>{app.settled?`${money(p.subtotal)} + ${money(p.service)} service`:p.subtotal?`${money(p.subtotal)} assigned · total pending`:'Waiting for the full split'}</small></div><strong>{app.settled?money(p.total):'—'}</strong></div>)}<div className="balance-line"><Check size={17}/>{app.settled?`${money(app.result!.sum)} verified · Every item counted once`:'Final totals appear after every question is resolved.'}</div></section>
   {!!app.activity.length&&<details className="activity"><summary>Conversation & changes <span>{app.activity.length}</span></summary><div>{app.activity.map((entry,i)=><p key={i} className={entry.kind}><span>{entry.kind==='voice'?'You said':entry.kind==='change'?'Updated':'Tabletalk'}</span>{entry.text}</p>)}</div></details>}
  </aside></div>
  {app.state&&<details className="evidence-panel"><summary><span><Info size={16}/>Session evidence</span><span>{app.example?'Allocation example':`${app.operations.length} recognition operations`}<ChevronRight size={16}/></span></summary><div className="evidence-content"><div><strong>{app.settledMs===null?'Not settled':`${(app.settledMs/1000).toFixed(1)}s`}</strong><span>Photo start to latest settled split<br/>(includes recording and decisions)</span></div><div><strong>{app.operations.length?`${incompleteCost?'≥ ':''}$${cost.toFixed(5)}`:'Not measured'}</strong><span>Estimated recognition cost<br/>{incompleteCost?'Some failed-call costs are unknown':'Hosting reported separately'}</span></div><button className="secondary-button" onClick={app.exportEvidence}><Download size={16}/>Export evidence</button></div>{app.recordings.length>0&&<div className="recordings">{app.recordings.map((rec,i)=><div key={rec.url}><span>Voice {i+1} · {rec.duration.toFixed(1)}s</span><audio controls src={rec.url}/><a href={rec.url} download={rec.name}>Download</a></div>)}</div>}<p className="evidence-note">{app.example?'This example uses prefilled receipt data and is not evidence of photo recognition. ':''}No automatic retries. All successful and failed recognition attempts are included in the export.</p></details>}
  <footer><details><summary>How the cents are split</summary><p>Shared items are divided equally between the selected people. Service is proportional to each person’s item subtotal. Remaining cents go to the largest fractional remainder; ties use the fixed table order (left to right). Amounts are calculated in integer cents. One shared item per receipt.</p></details><span>Your receipt stays in this session.</span></footer>
  <Dialog open={modal!==null} onOpenChange={open=>{if(!open)setModal(null);}}><DialogContent className={modal==='photo'?'photo-dialog':''}><DialogTitle>{modal==='names'?'Who’s at the table?':modal==='share'?'Share this item':modal==='photo'?'Original receipt':'Try a sample'}</DialogTitle><DialogDescription>{modal==='names'?'Use these names when you speak. You can change them any time.':modal==='share'?'Choose who shared it. We’ll divide the price equally.':modal==='photo'?'Check the recognized rows against the photo.':'Fictional receipt and synthetic voice recordings, with expected results saved before testing.'}</DialogDescription>
  {modal==='names'&&<form onSubmit={e=>{e.preventDefault();try{app.rename(names);setModal(null);}catch(error){setNameError(error instanceof Error?error.message:'Please check the names.');}}}><div className="name-fields">{names.map((name,i)=><label key={i}><span className={`avatar person-${i}`}>{i+1}</span><input aria-label={`Person ${i+1} name`} value={name} maxLength={30} onChange={e=>setNames(n=>n.map((x,j)=>i===j?e.target.value:x))}/></label>)}</div>{nameError&&<p className="error">{nameError}</p>}<button className="primary" type="submit">Save names</button></form>}
  {modal==='share'&&<><div className="share-choices">{app.people.map((p,i)=><label key={p.id} htmlFor={`share-${p.id}`}><Checkbox id={`share-${p.id}`} checked={sharers.includes(p.id)} onCheckedChange={checked=>setSharers(ids=>checked?[...ids,p.id]:ids.filter(id=>id!==p.id))}/><span className={`avatar person-${i}`}>{p.name[0]}</span>{p.name}</label>)}</div><button className="primary" disabled={!sharers.length||locked} onClick={()=>{app.assign([{itemIds:[shareItem],personIds:sharers}],`Shared ${items.find(i=>i.id===shareItem)?.name} between ${app.people.filter(p=>sharers.includes(p.id)).map(p=>p.name).join(', ')}.`);setModal(null);}}>Apply equal split</button></>}
  {modal==='photo'&&<img className="original-photo" src={app.photo} alt="Original restaurant receipt"/>}
  {modal==='sample'&&<div className="sample-content"><div className="sample-photo"><img src="/samples/receipt.png" alt="Table Nine sample receipt, total EUR 47.75"/><div><strong>Table Nine · €47.75</strong><p>Two coffees, three mains, shared fries and a service charge.</p><button className="primary" disabled={locked} onClick={()=>{setModal(null);void app.readSample(false);}}>Read sample photo</button><button className="text-button" disabled={locked} onClick={()=>{setModal(null);void app.readSample(true);}}>Try the unreadable version</button></div></div><div className="sample-audios">{[{id:'normal',label:'Normal split'},{id:'shared',label:'Shared fries'},{id:'before-correction',label:'Before the correction'},{id:'correction',label:'Correct the second coffee'},{id:'ambiguous',label:'An ambiguous coffee'}].map(sample=><div key={sample.id}><strong>{sample.label}</strong><audio controls preload="none" src={`/samples/${sample.id}.wav`}/><button className="quiet-button" disabled={!app.state||locked||app.configured===false} onClick={()=>{setModal(null);void app.useSampleAudio(sample.id);}}>Use recording</button></div>)}</div><button className="secondary-button" disabled={locked} onClick={()=>{setModal(null);app.startExample();}}>Explore allocation only · no recognition</button></div>}
  </DialogContent></Dialog>
 </main>;
}
